[build]
  base = "Frontend"
  command = "pwd && ls -la && npm --version && node --version && npm ci --verbose && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  NPM_FLAGS = "--no-audit --no-fund --legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 