[build]
  base = "Frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  VITE_CJS_IGNORE_WARNING = "true"
  VITE_CJS_TRACE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 