[build]
  base = "Frontend"
  command = "cd Frontend && npm ci && npm run build"
  publish = "Frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 